name: "Conftest"
description: "Write tests against structured configuration data using Open Policy Agent"
branding:
  icon: "check"
  color: "green"
inputs: 
  files:
    description: "Files and/or folders for Conftest to test (space delimited)"
    required: true
  policy:
    description: "Where to find the policy folder or file"
    default: "policy"
  data:
    description: "Files or folder with supplemental test data"
  all-namespaces:
    description: "Whether to use all namespaces in testing"
    default: true
  combine:
    description: "Whether to combine input files"
  pull-url:
    description: "URL to pull policies from"
  pull-secret:
    description: "Secret that allows the policies to be pulled"
  add-comment:
    description: "Whether or not to add a comment to the PR"
    default: true
  docs-url:
    description: "URL where users can find out more about the policies"
  no-fail:
    description: "Always returns an exit code of 0 (no error)"
  gh-token:
    description: "Token that allows us to post a comment in the PR"
  gh-comment-url:
    description: "URL of the comments for the PR"
  metrics-url:
    description: "URL to POST the results to for metrics"
  metrics-source:
    description: "Unique identifier for the source of the submission"
  metrics-details:
    description: "Whether to include the full test results in the metrics"
  metrics-token:
    description: "Bearer token for submitting metrics"
  policy-id-key:
    description: "Name of the key in the details object that stores the policy ID"
    default: "policyID"
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    FILES: ${{ inputs.files }}
    POLICY: ${{ inputs.policy }}
    DATA: ${{ inputs.data }}
    ALL_NAMESPACES: ${{ inputs.all-namespaces }}
    COMBINE: ${{ inputs.combine }}
    PULL_URL: ${{ inputs.pull-url }}
    PULL_SECRET: ${{ inputs.pull-secret }}
    ADD_COMMENT: ${{ inputs.add-comment }}
    DOCS_URL: ${{ inputs.docs-url }}
    NO_FAIL: ${{ inputs.no-fail }}
    GITHUB_TOKEN: ${{ inputs.gh-token }}
    GITHUB_COMMENT_URL: ${{ inputs.gh-comment-url }}
    METRICS_URL: ${{ inputs.metrics-url }}
    METRICS_SOURCE: ${{ inputs.metrics-source }}
    METRICS_DETAILS: ${{ inputs.metrics-details }}
    METRICS_TOKEN: ${{ inputs.metrics-token }}
    POLICY_ID_KEY: ${{ inputs.policy-id-key }}
